### ISSUE TITLE
Load More Button - UI Caters during the upload process

### ISSUE THREAD

**Issue by kjnanda** [rtCamp/rtMedia#1036] opened 2018-01-05 10:31 UTC
![media_ _adminuser_ _krupa_rtdemo_in](https://user-images.githubusercontent.com/15173772/34604125-b7f7a3c2-f22c-11e7-84b4-d7c0a5f34a37.jpg)

**Comment by malavvasita** [comment] 2018-10-09 06:08
@kjnanda Can you please verify if this issue exists in current version of rtMedia?

It seems to be fixed in rtMedia v4.5.0

Related issue link: #1084 
PR link: [#1111](https://github.com/rtMediaWP/rtMedia/pull/1111)

**Comment by kjnanda** [comment] 2018-10-09 06:17
@malavvasita I am not able to reproduce this issue. It seems fixed.

**Comment by kjnanda** [comment] 2019-03-01 09:15
This issue still present. Please follow the steps mentioned below to reproduce it.

-------

**Steps:**

1. Set Number of media on a page to `3`. (Keeping lower number but you can check with any number of media files) and **Media display pagination option** to load more
2. Upload media more than 3. E.g. 4
3. Reload the page after the upload is done. It will show the `load more button`.
4. Now, Delete 2 media files and reload the page
5. Upload 2 files again and observe that `load more` CSS is not applied properly.
6. After page refresh, it works fine.

-----

Please check this visual - https://goo.gl/Xr5EZx

----

```
Test Environment Used :

1. rtMedia version 4.5.6
2. Buddypress version 4.2.0
3. WP version 5.1
4. Issue appear in all browsers - Chrome, FireFox and Safari
```

**Comment by kjnanda** [comment] 2019-03-01 09:16
This issue also occurs while sorting media file using sort_parameters and when uploader is true. 

Steps : 
1. Write shortcode to sort media using sort parameters with uploader set to true.
2. Upload some media and observe that on uploading media, media gallery load more UI caters. 

![load-more](https://user-images.githubusercontent.com/41000648/49013913-4dfa9b00-f1a4-11e8-96b1-ecd584ded362.png)

**Comment by pavanpatil1** [comment] 2021-11-08 05:13
Hi @Pradeep1308, I have cross-checked the [PR](https://github.com/rtCamp/rtMedia/pull/1776) and found one regression issue. 
On rtMedia display settings, suppose if a number of media per page = 2 and only 2 media is present in album still the load more button is visible and if we click on load more `Oops !! There are no media found for the request !!` this message is displayed. 

Steps to reproduce the behavior:
1. Go to albums. open any album
2. delete the media from the album if more media is present than a number of media per page.

**Expected behavior**
load more button should not be visible if the number of media in the album is equal to the number of media per page. 

**Screenshots or Visual**

https://user-images.githubusercontent.com/44057535/140687662-00d8e4fb-b956-4551-96a8-a882998c5902.mp4


**Test Environment Used**
 - WordPress: v4.6.8
 - rtMedia- issue fix branch. 
 - Browser: chrome.

**Closed** 2021-11-08 12:57 UTC
Labels: bug
