### ISSUE TITLE
[Dashbaord] Hire Us tab - Correct the back ground color of the button

### ISSUE THREAD

**Issue by kjnanda** [rtCamp/rtMedia#1486] opened 2019-11-27 05:30 UTC
It should be `#007cba` color.

![Hire_Us_‹_test_—_WordPress](https://user-images.githubusercontent.com/15173772/69696206-fd928200-1104-11ea-904b-f710c3963668.png)

**Comment by vaishaliagola27** [comment] 2020-09-10 11:55
@pooja-muchandikar 

Please let me know if below button will be okay. 

<img width="625" alt="Screenshot 2020-09-10 at 5 24 35 PM" src="https://user-images.githubusercontent.com/11362577/92725950-8162e580-f38a-11ea-876f-80220649428b.png">

**Comment by pooja-muchandikar** [comment] 2020-09-10 11:56
@vaishaliagola27 

Yes, looks fine :+1:

**Comment by pooja-muchandikar** [comment] 2020-09-24 08:24
Tested with `pre-release` branch and the button looks fine. :heavy_check_mark:

**Comment by pooja-muchandikar** [comment] 2020-11-23 10:42
Tested with `master` branch and the issue is fixed.

**Comment by pooja-muchandikar** [comment] 2020-11-23 11:57
Released with `v4.6.5`

**Closed by pooja-muchandikar** 2020-11-23 11:57 UTC
Labels: Low, Tested, UI
