### ISSUE TITLE
Image is getting overlapped and breaking after uploading from media

### ISSUE THREAD

**Issue by Rink9** [rtCamp/rtMedia#1916] opened 2022-05-18 06:18 UTC
**Describe the bug**
Image is getting overlapped and breaking after uploading from media

**Testing Environment**
rtMedia for WordPress, BuddyPress and bbPress:  Version 4.6.11 
BuddyPress: Version 10.2.0
**WordPress development version (6.0-RC3-53407)**

**Steps to reproduce**

-  Navigate to media frontend
- Upload a image (If there is any existing image it will get overlapped) 

**Screencast:**

Image is getting overlapped

https://user-images.githubusercontent.com/44554636/168961284-a974e057-2b8a-41be-8610-f8a2f6195275.mp4

cc: @thebengalboy @pooja-muchandikar @pavanpatil1

**Comment by pooja-muchandikar** [comment] 2022-05-23 06:12
@Mukulsingh27 

Just an update here the image getting overlapped issue is happening with 2022 theme

**2022 Theme**
<img width="1253" alt="Screenshot 2022-05-23 at 11 39 41 AM" src="https://user-images.githubusercontent.com/41000648/169754373-185667dd-01ef-4ba0-b335-bd2ca1c8a15b.png">

---

**2021 Theme**
<img width="1262" alt="Screenshot 2022-05-23 at 11 40 01 AM" src="https://user-images.githubusercontent.com/41000648/169754451-00125428-1c76-487e-9e96-53a51636467f.png">

---

The other issue Bulk Edit buttons are open by default is happening in all themes. Let me know if you have further queries I will help to reproduce. 

cc: @Rink9

**Comment by Pradeep1308** [comment] 2022-05-31 10:02
@Rink9 Is this issue reproducible in the stable version of WP6.0. 
In my local this issue is not reproducible, I've tried with a fresh site.

cc: @thebengalboy @pooja-muchandikar @pavanpatil1

**Comment by pooja-muchandikar** [comment] 2022-06-01 05:24
@Pradeep1308 Me and Rinky faced this issue with stable version of WP6.0, but @pavanpatil1 was not able to reproduce. So this is kind of random issue generated with stable version of WP6.0 and all latest version of rtMedia, BuddyPress etc.

**Comment by Pradeep1308** [comment] 2022-06-02 16:43
Tried to reproduce again but not able to.
What to do next?
cc: @thebengalboy @pooja-muchandikar

**Comment by pooja-muchandikar** [comment] 2022-06-03 02:50
@Pradeep1308 please proceed with other issues. 

@pavanpatil1 @Rink9 Can you both try to reproduce the issues once with fresh set-up? If the issue is reproducible then please add proper steps to reproduce, if its not let us know we can take action on this issue accordingly.

**Comment by Rink9** [comment] 2022-06-03 07:25
@pooja-muchandikar I have tried to reproduce this issue with fresh site and also following some different different scenario somehow failed to reproduce this issue. We can close this issue for now. 

If this issue is reproducible in future will open this issue again. 

cc: @thebengalboy @pavanpatil1

**Comment by pooja-muchandikar** [comment] 2022-06-03 07:40
Thanks for the update @Rink9 

Closing this issue for now, we will revisit this issue if we face the similar problem in future.

cc: @Pradeep1308 @thebengalboy

**Closed by pooja-muchandikar** 2022-06-03 07:40 UTC
Labels: bug, UI, WP-6.0
