### ISSUE TITLE
Save settings button is not working, not getting "Settings saved successfully!" message

### ISSUE THREAD

**Issue by Rink9** [rtCamp/rtMedia#1883] opened 2022-04-08 07:42 UTC
**Describe the bug**
On Save settings button is not working, not getting "Settings saved successfully!" message

**To Reproduce**

1.  Go to rtMedia settings
2. After changing anything click on **Save settings**

**Expected behavior**
Will show message like "Settings saved successfully!"

**Screenshots**
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/44554636/162387813-104060d8-a3b3-435e-99df-2485be8b0a1e.png">

**Screencast:**

https://user-images.githubusercontent.com/44554636/162388993-309d37fb-075c-4295-94ba-b0cf9156e00e.mp4

**Test Environment Used**
 - WordPress: [Version 5.9.3]
 - BuddyPress: [Version 10.2.0]
 - rtMedia [Version 4.6.10]
 - rtMedia premium [pre-release branch] [Version 31.1]
 - Browser [Chrome]

**Additional context**
On single site it's working perfectly. But on multisite getting this issue.

cc: @thebengalboy

**Comment by thebengalboy** [comment] 2022-04-08 08:02
@Mukulsingh27 Once you are done with the current task on hand, please could you take care of this?

**Comment by Pradeep1308** [comment] 2022-04-11 07:50
@Rink9 This issue is not reproducible in my local, try with this branch fix/MU-errors of rtMedia premium and let me know if its still there.

**Comment by Rink9** [comment] 2022-04-11 10:20
@Pradeep1308 On my dev site when i tried with root domain https://lutfun-rinky.rt.gw/ , `save setting` button is working. But when i am trying with https://lutfun-rinky.rt.gw/rtmedia-addon-automation/ subdomain, `save setting` button is not working.

I am sharing my dev site credential with you on slack.

**Comment by Rink9** [comment] 2022-04-11 17:48
@Pradeep1308 Rechecked this issue as per discussion on call. I have deleted that `rtmedia-addon-automation` subdomain and created new one and clicked `save settings` . And it's working. Noticed that this issue not reproducible all the time.

**Comment by Pradeep1308** [comment] 2022-04-11 17:51
Thanks for the update @Rink9 , hence closing the issue.

**Comment by Rink9** [comment] 2022-04-11 18:03
@Pradeep1308 Somehow again facing this issue after creating the subdomain. I think this issue is not stable, sometime it reproduces and sometimes it's not. But IMO it's something major issue.

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/44554636/162801342-4e7249b0-3096-4f7c-b121-700603294b0d.png">

**Comment by Pradeep1308** [comment] 2022-04-11 18:09
@Rink9  Okay, I'll again check it and update.

**Comment by Pradeep1308** [comment] 2022-04-15 10:53
Hey, @Rink9 I've tried to reproduce it on local as well as on the dev site and tried to debug by looking at the console error but, still not able to reproduce it.

**Comment by Rink9** [comment] 2022-04-15 11:07
@Pradeep1308 On local it's not reproducible. One thing i am assuming but seems not logical but still i am explaining

Initially i could able to click on `save settings ` and it was saving the changes and showing the successful message. No error was on there. And after the automation purpose i have clicked so many times on `save settings` button. And then now it's not working. Showing also console error. Another thing i want to share is like i thought it's for MU site. but it's also occurring for single site. Don't know is it server related issue or anything else. That's all the information i can share from my end.

**MU Site**

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/44554636/163563689-2683fc9b-0e45-45ef-a0b8-c789ee1e2286.png">

**Single site**

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/44554636/163563942-ca710d1e-86d6-45f5-939a-dbceb4ef06ea.png">

cc: @pooja-muchandikar

**Comment by pooja-muchandikar** [comment] 2022-04-15 11:09
@Rink9 

Can you share your testing environment? It will help to debug the issue.

**Comment by Pradeep1308** [comment] 2022-04-15 11:14
@Rink9 just tell me one thing, without automation thing were this issue is reproducible?
I've tested with the latest BP version and pre-release of both core as well as Premium.

**Comment by Rink9** [comment] 2022-04-15 11:15
@pooja-muchandikar Same environment on my local and dev site. But it's not reproducible on local. But on dev site console error is showing. And i have mentioned the testing environment on issue description.

@Pradeep1308 As far now, NO. Because before automating everything went fine. 
Can you check the console error's on my dev site. Already shared credentials on your DM.

**Comment by pooja-muchandikar** [comment] 2022-04-15 11:16
rtMedia premium version? Or which branch is installed on your site?

**Comment by Rink9** [comment] 2022-04-15 11:20
rtMedia premium [pre-release branch] [Version 31.1]

**Comment by Pradeep1308** [comment] 2022-04-15 11:27
@Rink9 I've tested with your site, tried on a different subdomain on your site only, save setting is working fine with that.
I've tried to find things basis on the console error and couldn't find anything wrong with that too. 

@pooja-muchandikar what's your thought about it, because without automation thing it's working fine.

**Comment by pooja-muchandikar** [comment] 2022-04-15 11:31
@Pradeep1308 

I faced this without automation as well but now its not reproducible, but by the error from @Rink9 site do you see any root cause? If not let's wrap this issue here and make a note of this and check this while performing complete testing

**Comment by Pradeep1308** [comment] 2022-04-15 11:34
Yes by console error I've tried to debug to root cause and everything seems good @pooja-muchandikar 
Sure we can do that.

**Comment by Rink9** [comment] 2022-04-29 09:19
Hi. @Pradeep1308 Unfortunately I couldn't able to figure out the steps to reproduce this issue. Only i have gone through is on automation it clicked the save settings button multiple of times. I have already shared my credentials with you. You can check the console error.  When you have some time please take a look on this issue.

**Refer:** https://qa-automation.rt.gw/wp-admin/admin.php?page=rtmedia-settings#rtmedia-display

## Errors

`An invalid form control with name='rtmedia-options[general_jpeg_image_quality]' is not focusable.`
`An invalid form control with name='rtmedia-options[general_sitemapMaxEntries]' is not focusable.`

cc: @pavanpatil1 @pooja-muchandikar

**Comment by pooja-muchandikar** [comment] 2022-04-29 09:41
@pavanpatil1 Can you please try to reproduce the [issue](https://github.com/rtCamp/rtMedia/issues/1883#issuecomment-1113099145) shared by @Rink9

**Comment by thebengalboy** [comment] 2022-08-01 06:32
Closing the issue as this has been fixed. #1938

**Closed by thebengalboy** 2022-08-01 06:32 UTC
Labels: bug, Priority/High, on-hold
